import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Engineering',
      link: { type: 'doc', id: 'engineering/index' },
      items: [{ type: 'autogenerated', dirName: 'engineering' }],
    },
    {
      type: 'category',
      label: 'Publications',
      link: { type: 'doc', id: 'publications/index' },
      items: [{ type: 'autogenerated', dirName: 'publications' }],
    },
  ],
};

export default sidebars;
